// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package sqlc

import (
	"context"
)

type DBTX interface {
	Exec(context.Context, string, ...interface{}) (int64, error)
	Query(context.Context, string, ...interface{}) (Rows, error)
	QueryRow(context.Context, string, ...interface{}) Row
}

type Row interface {
	Scan(dest ...interface{}) error
}

type Rows interface {
	Close()
	Err() error
	Next() bool
	Scan(dest ...interface{}) error
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

type Queries struct {
	db DBTX
}

func (q *Queries) WithTx(tx DBTX) *Queries {
	return &Queries{
		db: tx,
	}
}

// Querier is the interface for all queries
type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, id int32) error
	GetUserByID(ctx context.Context, id int32) (User, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	CountUsers(ctx context.Context) (int64, error)
}

var _ Querier = (*Queries)(nil)
